REQUEST: PUT /dav/foo.html
STATUS: 401
REASON: Unauthorized
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 687
Content-Length: 213
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Unauthorized
Bobo-Exception-File: HTTPResponse.py
WWW-Authenticate: basic realm="Zope"
----------------------------------------------------------------------
<html>
  <head>
<base href="http://localhost:1980/dav/foo.html/" />
<title>foo.html</title></head>
  <body bgcolor="#FFFFFF">

 <strong>You are not authorized to access this resource.</strong>

  </body>
</html>


----------------------------------------------------------------------
REQUEST: OPTIONS /dav/foo.html
STATUS: 200
REASON: OK
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Accept-Ranges: none
Content-Length: 0
Allow: GET, HEAD, POST, PUT, DELETE, OPTIONS, TRACE, PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK
DAV: 1,2
----------------------------------------------------------------------

----------------------------------------------------------------------
REQUEST: DELETE /dav/foo.html
STATUS: 401
REASON: Unauthorized
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 687
Content-Length: 213
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Unauthorized
Bobo-Exception-File: HTTPResponse.py
WWW-Authenticate: basic realm="Zope"
----------------------------------------------------------------------
<html>
  <head>
<base href="http://localhost:1980/dav/foo.html/" />
<title>foo.html</title></head>
  <body bgcolor="#FFFFFF">

 <strong>You are not authorized to access this resource.</strong>

  </body>
</html>


----------------------------------------------------------------------
REQUEST: DELETE /dav/newdir
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: MKCOL /dav/newdir
STATUS: 409
REASON: Conflict
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 65
Content-Length: 828
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Conflict
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: Conflict</strong><br/>
      <strong>Error Value: Collection ancestors must already exist.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: MKCOL /dav/newdir/another
STATUS: 409
REASON: Conflict
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 65
Content-Length: 828
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Conflict
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: Conflict</strong><br/>
      <strong>Error Value: Collection ancestors must already exist.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPFIND /dav
STATUS: 401
REASON: Unauthorized
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 687
Content-Length: 200
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Unauthorized
Bobo-Exception-File: HTTPResponse.py
WWW-Authenticate: basic realm="Zope"
----------------------------------------------------------------------
<html>
  <head>
<base href="http://localhost:1980/dav/" />
<title>Zope</title></head>
  <body bgcolor="#FFFFFF">

 <strong>You are not authorized to access this resource.</strong>

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPFIND /dav
STATUS: 401
REASON: Unauthorized
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 687
Content-Length: 200
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Unauthorized
Bobo-Exception-File: HTTPResponse.py
WWW-Authenticate: basic realm="Zope"
----------------------------------------------------------------------
<html>
  <head>
<base href="http://localhost:1980/dav/" />
<title>Zope</title></head>
  <body bgcolor="#FFFFFF">

 <strong>You are not authorized to access this resource.</strong>

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPFIND /dav
STATUS: 401
REASON: Unauthorized
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 687
Content-Length: 200
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Unauthorized
Bobo-Exception-File: HTTPResponse.py
WWW-Authenticate: basic realm="Zope"
----------------------------------------------------------------------
<html>
  <head>
<base href="http://localhost:1980/dav/" />
<title>Zope</title></head>
  <body bgcolor="#FFFFFF">

 <strong>You are not authorized to access this resource.</strong>

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPFIND /dav
STATUS: 401
REASON: Unauthorized
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 687
Content-Length: 200
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Unauthorized
Bobo-Exception-File: HTTPResponse.py
WWW-Authenticate: basic realm="Zope"
----------------------------------------------------------------------
<html>
  <head>
<base href="http://localhost:1980/dav/" />
<title>Zope</title></head>
  <body bgcolor="#FFFFFF">

 <strong>You are not authorized to access this resource.</strong>

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPPATCH /dav
STATUS: 401
REASON: Unauthorized
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 687
Content-Length: 200
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Unauthorized
Bobo-Exception-File: HTTPResponse.py
WWW-Authenticate: basic realm="Zope"
----------------------------------------------------------------------
<html>
  <head>
<base href="http://localhost:1980/dav/" />
<title>Zope</title></head>
  <body bgcolor="#FFFFFF">

 <strong>You are not authorized to access this resource.</strong>

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPPATCH /dav
STATUS: 401
REASON: Unauthorized
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 687
Content-Length: 200
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Unauthorized
Bobo-Exception-File: HTTPResponse.py
WWW-Authenticate: basic realm="Zope"
----------------------------------------------------------------------
<html>
  <head>
<base href="http://localhost:1980/dav/" />
<title>Zope</title></head>
  <body bgcolor="#FFFFFF">

 <strong>You are not authorized to access this resource.</strong>

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PUT /dav/blah.cgi
STATUS: 409
REASON: Conflict
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 65
Content-Length: 828
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Conflict
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: Conflict</strong><br/>
      <strong>Error Value: Collection ancestors must already exist.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PUT /dav/file1
STATUS: 409
REASON: Conflict
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 65
Content-Length: 828
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Conflict
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: Conflict</strong><br/>
      <strong>Error Value: Collection ancestors must already exist.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: MOVE /dav/blah.cgi
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: COPY /dav/subdir
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPPATCH /dav/file1
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPFIND /dav/foo.cgi
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: DELETE /dav/testdata
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: MKCOL /dav/testdata
STATUS: 409
REASON: Conflict
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 65
Content-Length: 828
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Conflict
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: Conflict</strong><br/>
      <strong>Error Value: Collection ancestors must already exist.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PUT /dav/testdata/file1
STATUS: 409
REASON: Conflict
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 65
Content-Length: 828
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Conflict
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: Conflict</strong><br/>
      <strong>Error Value: Collection ancestors must already exist.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PUT /dav/testdata/file2
STATUS: 409
REASON: Conflict
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 65
Content-Length: 828
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Conflict
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: Conflict</strong><br/>
      <strong>Error Value: Collection ancestors must already exist.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PUT /dav/testdata/file3
STATUS: 409
REASON: Conflict
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 65
Content-Length: 828
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Conflict
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: Conflict</strong><br/>
      <strong>Error Value: Collection ancestors must already exist.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: MKCOL /dav/testdata/sub
STATUS: 409
REASON: Conflict
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 65
Content-Length: 828
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Conflict
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: Conflict</strong><br/>
      <strong>Error Value: Collection ancestors must already exist.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PUT /dav/testdata/sub/file1
STATUS: 409
REASON: Conflict
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 65
Content-Length: 828
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Conflict
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: Conflict</strong><br/>
      <strong>Error Value: Collection ancestors must already exist.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PUT /dav/testdata/sub/file2
STATUS: 409
REASON: Conflict
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 65
Content-Length: 828
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Conflict
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: Conflict</strong><br/>
      <strong>Error Value: Collection ancestors must already exist.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PUT /dav/testdata/sub/file3
STATUS: 409
REASON: Conflict
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 65
Content-Length: 828
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: Conflict
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: Conflict</strong><br/>
      <strong>Error Value: Collection ancestors must already exist.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPPATCH /dav/testdata
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPPATCH /dav/testdata/file1
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPPATCH /dav/testdata/file2
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPPATCH /dav/testdata/file3
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPPATCH /dav/testdata/sub
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPPATCH /dav/testdata/sub/file1
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPPATCH /dav/testdata/sub/file2
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:17 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPPATCH /dav/testdata/sub/file3
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:18 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: MOVE /dav/testdata/file1
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:18 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: MOVE /dav/testdata/sub
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:18 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: MOVE /dav/testdata/newsub/file2
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:18 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: COPY /dav/testdata/newsub/file3
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:18 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: COPY /dav/testdata/newsub/file1
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:18 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: COPY /dav/testdata/newsub
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:18 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
REQUEST: PROPFIND /dav/testdata
STATUS: 404
REASON: Not Found
Server: Zope/(Zope 2.9.7-final, python 2.4.4, linux2) ZServer/1.1
Date: Sat, 16 Jun 2007 09:30:18 GMT
Bobo-Exception-Line: 66
Content-Length: 825
Bobo-Exception-Value: See the server error log for details
Content-Type: text/html; charset=iso-8859-15
Bobo-Exception-Type: NotFound
Bobo-Exception-File: NullResource.py
----------------------------------------------------------------------
<html>
  <head><title>Zope</title></head>
  <body bgcolor="#FFFFFF">


  <h2>Site Error</h2>

  <p>An error was encountered while publishing this resource.
  </p>
  
  <p>
      <strong>Error Type: NotFound</strong><br/>
      <strong>Error Value: The requested resource was not found.</strong><br/> 
  </p>
 
  <hr noshade="noshade" />
 
  <p>Troubleshooting Suggestions</p>

  <ul>
            <li>The URL may be incorrect.</li>
      <li>The parameters passed to this resource may be incorrect.</li>
      <li>A resource that this resource relies on may be encountering
          an error.</li>
  </ul>

  <p>For more detailed information about the error, please
  refer to the error log.
  </p>

  <p>If the error persists please contact the site maintainer.
  Thank you for your patience.
  </p>

  

  </body>
</html>


----------------------------------------------------------------------
